name: "Publish tags to FlakeHub"
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to publish to FlakeHub"
        type: "string"
        required: true
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: "DeterminateSystems/nix-installer-action@00199f951aeb9404028a6e4b95ad42546f73296a" # main
      - uses: "DeterminateSystems/flakehub-push@bfc2781eb39e5b27112b6ea8ea48f7d6c8183d67" # main
        with:
          visibility: "public"
          name: "neumantm/vcard-studio-nix"
          tag: "${{ inputs.tag }}"
