name: "Test"
on:
  pull_request:
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
    - name: Install nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
    - name: Build
      env:
        NIXPKGS_ALLOW_UNFREE: 1
      run: nix build --impure
    - name: Flake Check
      env:
        NIXPKGS_ALLOW_UNFREE: 1
      run: nix flake check --impure --all-systems
